name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install gox
      run: |
        go get github.com/mitchellh/gox

    - name: Cross-compile binaries with gox
      run: |
        gox -osarch="darwin/amd64 darwin/arm64 windows/amd64 linux/amd64" -output "dist/key-manager_{{.OS}}_{{.Arch}}"

    - name: List the contents of the dist directory
      run: ls -la dist

    - name: Install FPM
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
        sudo gem install --no-document fpm

    - name: Build packages with FPM
      run: |
        fpm -s dir -t deb -n key-manager -v 1.0.0 ./dist/key-manager_linux_amd64=/usr/local/bin/key-manager_linux_amd64 ./install.sh=/usr/local/bin/install-key-manager.sh
        fpm -s dir -t rpm -n key-manager -v 1.0.0 ./dist/key-manager_linux_amd64=/usr/local/bin/key-manager_linux_amd64 ./install.sh=/usr/local/bin/install-key-manager.sh

    - name: Create Tarballs
      run: |
        tar czvf key-manager_linux_amd64.tar.gz -C dist key-manager_linux_amd64
        tar czvf key-manager_darwin_amd64.tar.gz -C dist key-manager_darwin_amd64
        tar czvf key-manager_darwin_arm64.tar.gz -C dist key-manager_darwin_arm64
        tar czvf key-manager_windows_amd64.tar.gz -C dist key-manager_windows_amd64.exe

    - name: Upload DEB package
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: '*.deb'

    - name: Upload RPM package
      uses: actions/upload-artifact@v2
      with:
        name: rpm-package
        path: '*.rpm'

    - name: Upload Tarballs
      uses: actions/upload-artifact@v2
      with:
        name: tarballs
        path: '*.tar.gz'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download DEB package
      uses: actions/download-artifact@v2
      with:
        name: deb-package

    - name: Download RPM package
      uses: actions/download-artifact@v2
      with:
        name: rpm-package

    - name: Download Tarballs
      uses: actions/download-artifact@v2
      with:
        name: tarballs

    - name: Upload DEB package to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'deb'
        owner: 'vladimirsduhovs'             # Your Cloudsmith account name or org name (namespace)
        repo: 'key-manager'         # Your Cloudsmith Repository name (slug)
        distro: 'ubuntu'           # Your Distribution (i.e Debian, Ubuntu)
        release: 'trusty'          # Your Distribution Release (i.e xenial, buster)
        republish: 'true'          # needed ONLY if version is not changing
        file: '*.deb'              # debian package filename

    - name: Upload Darwin AMD64 Tarball to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'raw'
        owner: 'vladimirsduhovs'
        repo: 'key-manager'
        file: 'key-manager_darwin_amd64.tar.gz'
        name: 'key-manager_darwin_amd64'
        summary: 'key-manager summary'
        description: 'key-manager description'
        version: ${{ github.sha }}

    - name: Upload Darwin ARM64 Tarball to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'raw'
        owner: 'vladimirsduhovs'
        repo: 'key-manager'
        file: 'key-manager_darwin_arm64.tar.gz'
        name: 'key-manager_darwin_arm64'
        summary: 'key-manager summary'
        description: 'key-manager description'
        version: ${{ github.sha }}

    - name: Upload Linux AMD64 Tarball to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'raw'
        owner: 'vladimirsduhovs'
        repo: 'key-manager'
        file: 'key-manager_linux_amd64.tar.gz'
        name: 'key-manager_linux_amd64'
        summary: 'key-manager summary'
        description: 'key-manager description'
        version: ${{ github.sha }}

    - name: Upload Windows AMD64 Tarball to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'raw'
        owner: 'vladimirsduhovs'
        repo: 'key-manager'
        file: 'key-manager_windows_amd64.tar.gz'
        name: 'key-manager_windows_amd64'
        summary: 'key-manager summary'
        description: 'key-manager description'
        version: ${{ github.sha }}
