    - name: Create Tarballs
      run: |
        tar czvf key-manager_linux_amd64.tar.gz -C dist key-manager_linux_amd64
        tar czvf key-manager_darwin_amd64.tar.gz -C dist key-manager_darwin_amd64
        tar czvf key-manager_darwin_arm64.tar.gz -C dist key-manager_darwin_arm64
        tar czvf key-manager_windows_amd64.tar.gz -C dist key-manager_windows_amd64.exe
