name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o key-manager

    - name: Install FPM
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
        sudo gem install --no-document fpm

    - name: Build packages with FPM
      run: |
        fpm -s dir -t deb -n key-manager -v 1.0.0 ./key-manager=/usr/local/bin/key-manager ./install.sh=/usr/local/bin/install-key-manager.sh
        fpm -s dir -t rpm -n key-manager -v 1.0.0 ./key-manager=/usr/local/bin/key-manager ./install.sh=/usr/local/bin/install-key-manager.sh

    - name: Upload DEB package
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: '*.deb'

    - name: Upload RPM package
      uses: actions/upload-artifact@v2
      with:
        name: rpm-package
        path: '*.rpm'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download DEB package
      uses: actions/download-artifact@v2
      with:
        name: deb-package

    - name: Download RPM package
      uses: actions/download-artifact@v2
      with:
        name: rpm-package

    - name: Upload DEB package to packagecloud
      uses: danielmundi/upload-packagecloud@v1
      with:
        PACKAGE-NAME: '*.deb'
        PACKAGECLOUD-USERNAME: ${{ secrets.PACKAGECLOUD_USERNAME }}
        PACKAGECLOUD-REPO: ${{ secrets.PACKAGECLOUD_REPOSITORY }}
        PACKAGECLOUD-DISTRIB: 'ubuntu/trusty'
        PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_API_TOKEN }}

    - name: Upload RPM package to packagecloud
      uses: danielmundi/upload-packagecloud@v1
      with:
        PACKAGE-NAME: '*.rpm'
        PACKAGECLOUD-USERNAME: ${{ secrets.PACKAGECLOUD_USERNAME }}
        PACKAGECLOUD-REPO: ${{ secrets.PACKAGECLOUD_REPOSITORY }}
        PACKAGECLOUD-DISTRIB: 'enterprise_linux/8'
        PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_API_TOKEN }}
